services:
  - type: web
    name: attendx-proxy-server
    env: docker
    plan: free
    region: singapore
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: QR_SECRET
        sync: false
